title: batra.blog # Replace with your blog title
author: Parth Batra # Replace with your name
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: batra99 # Replace with your Twitter username
github_username:  parth.batra99 # Replace with your GitHub username

theme: minima

plugins:
  - jekyll-toc

