title: Parth Batra | batra.blog # Replace with your blog title
author: Parth Batra # Replace with your name
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://parthbatra99.github.io" # replace yourusername with your GitHub username
twitter_username: batra99 # Replace with your Twitter username
github_username:  parth.batra99 # Replace with your GitHub username

theme: minima

plugins:
  - jekyll-toc

