title: My Awesome Blog # Replace with your blog title
author: Your Name # Replace with your name
email: your-email@example.com # Replace with your email
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb # Replace with your Twitter username
github_username:  jekyll # Replace with your GitHub username

theme: minima

plugins:
  - jekyll-toc

